stages:
  - .pre #not necessary to include, can be omitted since is sys defined
  - build
  - test

build website:
  image: node:16-alpine
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

.linter:
  image: node:16-alpine
  stage: .pre
  script:
    - yarn install
    - yarn lint

test website:
  image: node:16-alpine
  stage: test
  script:
    - yarn global add serve
    - serve -s build

.unit test:
  image: node:16-alpine
  stage: .pre
  script:
    - yarn install
    - yarn test

